import type { Interest, Book } from '../types';

export const INTERESTS: Interest[] = [
  { id: 1, name: 'Artificial Intelligence', icon: 'neurology', desc: 'Neural networks, LLMs, and ethics.' },
  { id: 2, name: 'Machine Learning', icon: 'memory', desc: 'Algorithms and predictive modeling.' },
  { id: 3, name: 'Data Science', icon: 'database', desc: 'Big data, analytics, and visualization.' },
  { id: 4, name: 'Java Programming', icon: 'terminal', desc: 'Enterprise development and JVM.' },
  { id: 5, name: 'Python', icon: 'code', desc: 'Scripting, automation, and science.' },
  { id: 6, name: 'Web Development', icon: 'html', desc: 'Full-stack, React, and modern CSS.' },
  { id: 7, name: 'Cyber Security', icon: 'shield_lock', desc: 'Ethical hacking and network defense.' },
  { id: 8, name: 'Cloud Computing', icon: 'cloud', desc: 'AWS, Azure, and infrastructure.' },
  { id: 9, name: 'Mobile App Dev', icon: 'smartphone', desc: 'iOS, Android, and Flutter.' },
  { id: 10, name: 'UI/UX Design', icon: 'palette', desc: 'Product design and user research.' },
  { id: 11, name: 'Business', icon: 'business_center', desc: 'Strategy and corporate growth.' },
  { id: 12, name: 'Entrepreneurship', icon: 'rocket_launch', desc: 'Startups and building ventures.' },
  { id: 13, name: 'Finance', icon: 'payments', desc: 'Markets, personal finance, and crypto.' },
  { id: 14, name: 'Marketing', icon: 'campaign', desc: 'Branding and digital advertising.' },
  { id: 15, name: 'Self Help', icon: 'psychology_alt', desc: 'Personal growth and mindset.' },
  { id: 16, name: 'Productivity', icon: 'timer', desc: 'Time management and workflows.' },
  { id: 17, name: 'Science', icon: 'science', desc: 'Physics, biology, and the universe.' },
  { id: 18, name: 'History', icon: 'history_edu', desc: 'Past civilizations and events.' },
  { id: 19, name: 'Biography', icon: 'person_book', desc: 'Stories of influential lives.' },
  { id: 20, name: 'Fantasy', icon: 'auto_fix_high', desc: 'Magic systems and world building.' },
  { id: 21, name: 'Mystery', icon: 'search_check', desc: 'Thrillers and investigative plots.' },
  { id: 22, name: 'Romance', icon: 'favorite', desc: 'Relationships and emotional journeys.' },
  { id: 23, name: 'Horror', icon: 'dark_mode', desc: 'Supernatural and psychological fear.' },
  { id: 24, name: 'Health & Fitness', icon: 'fitness_center', desc: 'Nutrition and physical wellness.' },
  { id: 25, name: 'Psychology', icon: 'psychology', desc: 'Behavior and the human mind.' },
];

export const RECOMMENDED_BOOKS: Book[] = [
  {
    id: '1',
    title: 'Placeholder Book Title 1',
    author: 'Alan Turing III',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.1,
    category: 'Machine Learning',
    matchPercent: 96,
    description: 'This is a detailed description for book 1. It explores the profound implications of machine learning and how it intersects with modern technology.',
    publicationYear: 2017,
    language: 'English',
    pages: 328,
    aiSummary: 'A comprehensive guide on Machine Learning. Key takeaways include practical applications and ethical considerations.',
    keywords: ['machine', 'technology', 'future'],
    similarBooks: ['16', '12']
  },
  {
    id: '2',
    title: 'Placeholder Book Title 2',
    author: 'Gene Hacker',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.2,
    category: 'Data Science',
    matchPercent: 78,
    description: 'This is a detailed description for book 2. It explores the profound implications of data science and how it intersects with modern technology.',
    publicationYear: 2017,
    language: 'English',
    pages: 401,
    aiSummary: 'A comprehensive guide on Data Science. Key takeaways include practical applications and ethical considerations.',
    keywords: ['data', 'technology', 'future'],
    similarBooks: ['34', '15']
  },
  {
    id: '3',
    title: 'Placeholder Book Title 3',
    author: 'S. Schrodinger',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 3.9,
    category: 'Philosophy',
    matchPercent: 91,
    description: 'This is a detailed description for book 3. It explores the profound implications of philosophy and how it intersects with modern technology.',
    publicationYear: 2015,
    language: 'English',
    pages: 270,
    aiSummary: 'A comprehensive guide on Philosophy. Key takeaways include practical applications and ethical considerations.',
    keywords: ['philosophy', 'technology', 'future'],
    similarBooks: ['31', '34']
  },
  {
    id: '4',
    title: 'Placeholder Book Title 4',
    author: 'Ada Lovelace Jr',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.6,
    category: 'Science',
    matchPercent: 94,
    description: 'This is a detailed description for book 4. It explores the profound implications of science and how it intersects with modern technology.',
    publicationYear: 2015,
    language: 'English',
    pages: 203,
    aiSummary: 'A comprehensive guide on Science. Key takeaways include practical applications and ethical considerations.',
    keywords: ['science', 'technology', 'future'],
    similarBooks: ['40', '23']
  },
  {
    id: '5',
    title: 'Placeholder Book Title 5',
    author: 'Elon M.',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.8,
    category: 'Business',
    matchPercent: 99,
    description: 'This is a detailed description for book 5. It explores the profound implications of business and how it intersects with modern technology.',
    publicationYear: 2018,
    language: 'English',
    pages: 212,
    aiSummary: 'A comprehensive guide on Business. Key takeaways include practical applications and ethical considerations.',
    keywords: ['business', 'technology', 'future'],
    similarBooks: ['33', '10']
  },
  {
    id: '6',
    title: 'Placeholder Book Title 6',
    author: 'Nikola T.',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 3.6,
    category: 'Web Development',
    matchPercent: 91,
    description: 'This is a detailed description for book 6. It explores the profound implications of web development and how it intersects with modern technology.',
    publicationYear: 2017,
    language: 'English',
    pages: 481,
    aiSummary: 'A comprehensive guide on Web Development. Key takeaways include practical applications and ethical considerations.',
    keywords: ['web', 'technology', 'future'],
    similarBooks: ['5', '4']
  },
  {
    id: '7',
    title: 'Placeholder Book Title 7',
    author: 'Dr. Sarah Vance',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 3.6,
    category: 'Artificial Intelligence',
    matchPercent: 97,
    description: 'This is a detailed description for book 7. It explores the profound implications of artificial intelligence and how it intersects with modern technology.',
    publicationYear: 2017,
    language: 'English',
    pages: 349,
    aiSummary: 'A comprehensive guide on Artificial Intelligence. Key takeaways include practical applications and ethical considerations.',
    keywords: ['artificial', 'technology', 'future'],
    similarBooks: ['21', '39']
  },
  {
    id: '8',
    title: 'Placeholder Book Title 8',
    author: 'Alan Turing III',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.3,
    category: 'Machine Learning',
    matchPercent: 77,
    description: 'This is a detailed description for book 8. It explores the profound implications of machine learning and how it intersects with modern technology.',
    publicationYear: 2019,
    language: 'English',
    pages: 499,
    aiSummary: 'A comprehensive guide on Machine Learning. Key takeaways include practical applications and ethical considerations.',
    keywords: ['machine', 'technology', 'future'],
    similarBooks: ['34', '5']
  },
  {
    id: '9',
    title: 'Placeholder Book Title 9',
    author: 'Gene Hacker',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 3.8,
    category: 'Data Science',
    matchPercent: 95,
    description: 'This is a detailed description for book 9. It explores the profound implications of data science and how it intersects with modern technology.',
    publicationYear: 2021,
    language: 'English',
    pages: 591,
    aiSummary: 'A comprehensive guide on Data Science. Key takeaways include practical applications and ethical considerations.',
    keywords: ['data', 'technology', 'future'],
    similarBooks: ['12', '6']
  },
  {
    id: '10',
    title: 'Placeholder Book Title 10',
    author: 'S. Schrodinger',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.3,
    category: 'Philosophy',
    matchPercent: 77,
    description: 'This is a detailed description for book 10. It explores the profound implications of philosophy and how it intersects with modern technology.',
    publicationYear: 2021,
    language: 'English',
    pages: 306,
    aiSummary: 'A comprehensive guide on Philosophy. Key takeaways include practical applications and ethical considerations.',
    keywords: ['philosophy', 'technology', 'future'],
    similarBooks: ['27', '27']
  },
  {
    id: '11',
    title: 'Placeholder Book Title 11',
    author: 'Ada Lovelace Jr',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.9,
    category: 'Science',
    matchPercent: 99,
    description: 'This is a detailed description for book 11. It explores the profound implications of science and how it intersects with modern technology.',
    publicationYear: 2019,
    language: 'English',
    pages: 433,
    aiSummary: 'A comprehensive guide on Science. Key takeaways include practical applications and ethical considerations.',
    keywords: ['science', 'technology', 'future'],
    similarBooks: ['6', '11']
  },
  {
    id: '12',
    title: 'Placeholder Book Title 12',
    author: 'Elon M.',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 3.6,
    category: 'Business',
    matchPercent: 85,
    description: 'This is a detailed description for book 12. It explores the profound implications of business and how it intersects with modern technology.',
    publicationYear: 2015,
    language: 'English',
    pages: 378,
    aiSummary: 'A comprehensive guide on Business. Key takeaways include practical applications and ethical considerations.',
    keywords: ['business', 'technology', 'future'],
    similarBooks: ['38', '37']
  },
  {
    id: '13',
    title: 'Placeholder Book Title 13',
    author: 'Nikola T.',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.6,
    category: 'Web Development',
    matchPercent: 99,
    description: 'This is a detailed description for book 13. It explores the profound implications of web development and how it intersects with modern technology.',
    publicationYear: 2015,
    language: 'English',
    pages: 294,
    aiSummary: 'A comprehensive guide on Web Development. Key takeaways include practical applications and ethical considerations.',
    keywords: ['web', 'technology', 'future'],
    similarBooks: ['37', '3']
  },
  {
    id: '14',
    title: 'Placeholder Book Title 14',
    author: 'Dr. Sarah Vance',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.7,
    category: 'Artificial Intelligence',
    matchPercent: 78,
    description: 'This is a detailed description for book 14. It explores the profound implications of artificial intelligence and how it intersects with modern technology.',
    publicationYear: 2023,
    language: 'English',
    pages: 473,
    aiSummary: 'A comprehensive guide on Artificial Intelligence. Key takeaways include practical applications and ethical considerations.',
    keywords: ['artificial', 'technology', 'future'],
    similarBooks: ['24', '4']
  },
  {
    id: '15',
    title: 'Placeholder Book Title 15',
    author: 'Alan Turing III',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.3,
    category: 'Machine Learning',
    matchPercent: 92,
    description: 'This is a detailed description for book 15. It explores the profound implications of machine learning and how it intersects with modern technology.',
    publicationYear: 2020,
    language: 'English',
    pages: 382,
    aiSummary: 'A comprehensive guide on Machine Learning. Key takeaways include practical applications and ethical considerations.',
    keywords: ['machine', 'technology', 'future'],
    similarBooks: ['39', '4']
  },
  {
    id: '16',
    title: 'Placeholder Book Title 16',
    author: 'Gene Hacker',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.7,
    category: 'Data Science',
    matchPercent: 85,
    description: 'This is a detailed description for book 16. It explores the profound implications of data science and how it intersects with modern technology.',
    publicationYear: 2019,
    language: 'English',
    pages: 360,
    aiSummary: 'A comprehensive guide on Data Science. Key takeaways include practical applications and ethical considerations.',
    keywords: ['data', 'technology', 'future'],
    similarBooks: ['33', '25']
  },
  {
    id: '17',
    title: 'Placeholder Book Title 17',
    author: 'S. Schrodinger',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 3.6,
    category: 'Philosophy',
    matchPercent: 73,
    description: 'This is a detailed description for book 17. It explores the profound implications of philosophy and how it intersects with modern technology.',
    publicationYear: 2019,
    language: 'English',
    pages: 259,
    aiSummary: 'A comprehensive guide on Philosophy. Key takeaways include practical applications and ethical considerations.',
    keywords: ['philosophy', 'technology', 'future'],
    similarBooks: ['18', '8']
  },
  {
    id: '18',
    title: 'Placeholder Book Title 18',
    author: 'Ada Lovelace Jr',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 3.7,
    category: 'Science',
    matchPercent: 98,
    description: 'This is a detailed description for book 18. It explores the profound implications of science and how it intersects with modern technology.',
    publicationYear: 2021,
    language: 'English',
    pages: 234,
    aiSummary: 'A comprehensive guide on Science. Key takeaways include practical applications and ethical considerations.',
    keywords: ['science', 'technology', 'future'],
    similarBooks: ['28', '9']
  },
  {
    id: '19',
    title: 'Placeholder Book Title 19',
    author: 'Elon M.',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.0,
    category: 'Business',
    matchPercent: 79,
    description: 'This is a detailed description for book 19. It explores the profound implications of business and how it intersects with modern technology.',
    publicationYear: 2015,
    language: 'English',
    pages: 255,
    aiSummary: 'A comprehensive guide on Business. Key takeaways include practical applications and ethical considerations.',
    keywords: ['business', 'technology', 'future'],
    similarBooks: ['21', '38']
  },
  {
    id: '20',
    title: 'Placeholder Book Title 20',
    author: 'Nikola T.',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.2,
    category: 'Web Development',
    matchPercent: 89,
    description: 'This is a detailed description for book 20. It explores the profound implications of web development and how it intersects with modern technology.',
    publicationYear: 2023,
    language: 'English',
    pages: 331,
    aiSummary: 'A comprehensive guide on Web Development. Key takeaways include practical applications and ethical considerations.',
    keywords: ['web', 'technology', 'future'],
    similarBooks: ['24', '19']
  },
  {
    id: '21',
    title: 'Placeholder Book Title 21',
    author: 'Dr. Sarah Vance',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.4,
    category: 'Artificial Intelligence',
    matchPercent: 77,
    description: 'This is a detailed description for book 21. It explores the profound implications of artificial intelligence and how it intersects with modern technology.',
    publicationYear: 2023,
    language: 'English',
    pages: 509,
    aiSummary: 'A comprehensive guide on Artificial Intelligence. Key takeaways include practical applications and ethical considerations.',
    keywords: ['artificial', 'technology', 'future'],
    similarBooks: ['3', '1']
  },
  {
    id: '22',
    title: 'Placeholder Book Title 22',
    author: 'Alan Turing III',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.0,
    category: 'Machine Learning',
    matchPercent: 92,
    description: 'This is a detailed description for book 22. It explores the profound implications of machine learning and how it intersects with modern technology.',
    publicationYear: 2019,
    language: 'English',
    pages: 514,
    aiSummary: 'A comprehensive guide on Machine Learning. Key takeaways include practical applications and ethical considerations.',
    keywords: ['machine', 'technology', 'future'],
    similarBooks: ['39', '23']
  },
  {
    id: '23',
    title: 'Placeholder Book Title 23',
    author: 'Gene Hacker',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.5,
    category: 'Data Science',
    matchPercent: 70,
    description: 'This is a detailed description for book 23. It explores the profound implications of data science and how it intersects with modern technology.',
    publicationYear: 2021,
    language: 'English',
    pages: 252,
    aiSummary: 'A comprehensive guide on Data Science. Key takeaways include practical applications and ethical considerations.',
    keywords: ['data', 'technology', 'future'],
    similarBooks: ['4', '32']
  },
  {
    id: '24',
    title: 'Placeholder Book Title 24',
    author: 'S. Schrodinger',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.0,
    category: 'Philosophy',
    matchPercent: 98,
    description: 'This is a detailed description for book 24. It explores the profound implications of philosophy and how it intersects with modern technology.',
    publicationYear: 2023,
    language: 'English',
    pages: 325,
    aiSummary: 'A comprehensive guide on Philosophy. Key takeaways include practical applications and ethical considerations.',
    keywords: ['philosophy', 'technology', 'future'],
    similarBooks: ['22', '24']
  },
  {
    id: '25',
    title: 'Placeholder Book Title 25',
    author: 'Ada Lovelace Jr',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.1,
    category: 'Science',
    matchPercent: 91,
    description: 'This is a detailed description for book 25. It explores the profound implications of science and how it intersects with modern technology.',
    publicationYear: 2015,
    language: 'English',
    pages: 492,
    aiSummary: 'A comprehensive guide on Science. Key takeaways include practical applications and ethical considerations.',
    keywords: ['science', 'technology', 'future'],
    similarBooks: ['10', '21']
  },
  {
    id: '26',
    title: 'Placeholder Book Title 26',
    author: 'Elon M.',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 3.8,
    category: 'Business',
    matchPercent: 99,
    description: 'This is a detailed description for book 26. It explores the profound implications of business and how it intersects with modern technology.',
    publicationYear: 2023,
    language: 'English',
    pages: 584,
    aiSummary: 'A comprehensive guide on Business. Key takeaways include practical applications and ethical considerations.',
    keywords: ['business', 'technology', 'future'],
    similarBooks: ['38', '36']
  },
  {
    id: '27',
    title: 'Placeholder Book Title 27',
    author: 'Nikola T.',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.0,
    category: 'Web Development',
    matchPercent: 72,
    description: 'This is a detailed description for book 27. It explores the profound implications of web development and how it intersects with modern technology.',
    publicationYear: 2021,
    language: 'English',
    pages: 263,
    aiSummary: 'A comprehensive guide on Web Development. Key takeaways include practical applications and ethical considerations.',
    keywords: ['web', 'technology', 'future'],
    similarBooks: ['1', '28']
  },
  {
    id: '28',
    title: 'Placeholder Book Title 28',
    author: 'Dr. Sarah Vance',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 3.7,
    category: 'Artificial Intelligence',
    matchPercent: 75,
    description: 'This is a detailed description for book 28. It explores the profound implications of artificial intelligence and how it intersects with modern technology.',
    publicationYear: 2017,
    language: 'English',
    pages: 510,
    aiSummary: 'A comprehensive guide on Artificial Intelligence. Key takeaways include practical applications and ethical considerations.',
    keywords: ['artificial', 'technology', 'future'],
    similarBooks: ['10', '20']
  },
  {
    id: '29',
    title: 'Placeholder Book Title 29',
    author: 'Alan Turing III',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.6,
    category: 'Machine Learning',
    matchPercent: 77,
    description: 'This is a detailed description for book 29. It explores the profound implications of machine learning and how it intersects with modern technology.',
    publicationYear: 2019,
    language: 'English',
    pages: 297,
    aiSummary: 'A comprehensive guide on Machine Learning. Key takeaways include practical applications and ethical considerations.',
    keywords: ['machine', 'technology', 'future'],
    similarBooks: ['14', '6']
  },
  {
    id: '30',
    title: 'Placeholder Book Title 30',
    author: 'Gene Hacker',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 3.9,
    category: 'Data Science',
    matchPercent: 84,
    description: 'This is a detailed description for book 30. It explores the profound implications of data science and how it intersects with modern technology.',
    publicationYear: 2019,
    language: 'English',
    pages: 405,
    aiSummary: 'A comprehensive guide on Data Science. Key takeaways include practical applications and ethical considerations.',
    keywords: ['data', 'technology', 'future'],
    similarBooks: ['23', '11']
  },
  {
    id: '31',
    title: 'Placeholder Book Title 31',
    author: 'S. Schrodinger',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 3.6,
    category: 'Philosophy',
    matchPercent: 92,
    description: 'This is a detailed description for book 31. It explores the profound implications of philosophy and how it intersects with modern technology.',
    publicationYear: 2019,
    language: 'English',
    pages: 430,
    aiSummary: 'A comprehensive guide on Philosophy. Key takeaways include practical applications and ethical considerations.',
    keywords: ['philosophy', 'technology', 'future'],
    similarBooks: ['4', '16']
  },
  {
    id: '32',
    title: 'Placeholder Book Title 32',
    author: 'Ada Lovelace Jr',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 5.0,
    category: 'Science',
    matchPercent: 81,
    description: 'This is a detailed description for book 32. It explores the profound implications of science and how it intersects with modern technology.',
    publicationYear: 2018,
    language: 'English',
    pages: 348,
    aiSummary: 'A comprehensive guide on Science. Key takeaways include practical applications and ethical considerations.',
    keywords: ['science', 'technology', 'future'],
    similarBooks: ['24', '4']
  },
  {
    id: '33',
    title: 'Placeholder Book Title 33',
    author: 'Elon M.',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 3.6,
    category: 'Business',
    matchPercent: 96,
    description: 'This is a detailed description for book 33. It explores the profound implications of business and how it intersects with modern technology.',
    publicationYear: 2020,
    language: 'English',
    pages: 375,
    aiSummary: 'A comprehensive guide on Business. Key takeaways include practical applications and ethical considerations.',
    keywords: ['business', 'technology', 'future'],
    similarBooks: ['28', '10']
  },
  {
    id: '34',
    title: 'Placeholder Book Title 34',
    author: 'Nikola T.',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.1,
    category: 'Web Development',
    matchPercent: 84,
    description: 'This is a detailed description for book 34. It explores the profound implications of web development and how it intersects with modern technology.',
    publicationYear: 2019,
    language: 'English',
    pages: 358,
    aiSummary: 'A comprehensive guide on Web Development. Key takeaways include practical applications and ethical considerations.',
    keywords: ['web', 'technology', 'future'],
    similarBooks: ['22', '29']
  },
  {
    id: '35',
    title: 'Placeholder Book Title 35',
    author: 'Dr. Sarah Vance',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.5,
    category: 'Artificial Intelligence',
    matchPercent: 74,
    description: 'This is a detailed description for book 35. It explores the profound implications of artificial intelligence and how it intersects with modern technology.',
    publicationYear: 2019,
    language: 'English',
    pages: 350,
    aiSummary: 'A comprehensive guide on Artificial Intelligence. Key takeaways include practical applications and ethical considerations.',
    keywords: ['artificial', 'technology', 'future'],
    similarBooks: ['22', '4']
  },
  {
    id: '36',
    title: 'Placeholder Book Title 36',
    author: 'Alan Turing III',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.5,
    category: 'Machine Learning',
    matchPercent: 77,
    description: 'This is a detailed description for book 36. It explores the profound implications of machine learning and how it intersects with modern technology.',
    publicationYear: 2019,
    language: 'English',
    pages: 384,
    aiSummary: 'A comprehensive guide on Machine Learning. Key takeaways include practical applications and ethical considerations.',
    keywords: ['machine', 'technology', 'future'],
    similarBooks: ['7', '32']
  },
  {
    id: '37',
    title: 'Placeholder Book Title 37',
    author: 'Gene Hacker',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.6,
    category: 'Data Science',
    matchPercent: 70,
    description: 'This is a detailed description for book 37. It explores the profound implications of data science and how it intersects with modern technology.',
    publicationYear: 2020,
    language: 'English',
    pages: 457,
    aiSummary: 'A comprehensive guide on Data Science. Key takeaways include practical applications and ethical considerations.',
    keywords: ['data', 'technology', 'future'],
    similarBooks: ['27', '26']
  },
  {
    id: '38',
    title: 'Placeholder Book Title 38',
    author: 'S. Schrodinger',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.6,
    category: 'Philosophy',
    matchPercent: 82,
    description: 'This is a detailed description for book 38. It explores the profound implications of philosophy and how it intersects with modern technology.',
    publicationYear: 2021,
    language: 'English',
    pages: 355,
    aiSummary: 'A comprehensive guide on Philosophy. Key takeaways include practical applications and ethical considerations.',
    keywords: ['philosophy', 'technology', 'future'],
    similarBooks: ['9', '15']
  },
  {
    id: '39',
    title: 'Placeholder Book Title 39',
    author: 'Ada Lovelace Jr',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.6,
    category: 'Science',
    matchPercent: 92,
    description: 'This is a detailed description for book 39. It explores the profound implications of science and how it intersects with modern technology.',
    publicationYear: 2016,
    language: 'English',
    pages: 350,
    aiSummary: 'A comprehensive guide on Science. Key takeaways include practical applications and ethical considerations.',
    keywords: ['science', 'technology', 'future'],
    similarBooks: ['5', '6']
  },
  {
    id: '40',
    title: 'Placeholder Book Title 40',
    author: 'Elon M.',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXBOCte-y-7SEBz3oRgIWXzWg_8agIpIZJV8Ud2Twwnu0zYjKxLNMYXsUnZN66cZfNe9SujbqxII3A3qZ5BaJKupS-yM0uS2_hDmI6BtYs5clXJ_lDROjZqPM-iwMUFujxazT5iWsr4BgwAzH-xv-9HM3X1W_hOtdH3d7SkxQRTsWr4dqsv6IszkzKXT7aNAmHkJ44OM173zEtVBtmpYD7VnRQv1Nwnw_dFn-mWdpgF5QdlV0ohsg',
    rating: 4.0,
    category: 'Business',
    matchPercent: 79,
    description: 'This is a detailed description for book 40. It explores the profound implications of business and how it intersects with modern technology.',
    publicationYear: 2015,
    language: 'English',
    pages: 325,
    aiSummary: 'A comprehensive guide on Business. Key takeaways include practical applications and ethical considerations.',
    keywords: ['business', 'technology', 'future'],
    similarBooks: ['2', '10']
  }
];

export const CONTINUE_READING_BOOKS: Book[] = [
  {
    id: 'cr1',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDSKnVEonpoF6piegl0bPhaNO2LWaQM-_i6xNfd-ku0CvEMveKhTMA_henqf3GgcsTV4qiHCYkgB25vmAuVkMeeHLqQ4iXR1ESObpU1gh_-w6BLfwrFSmS8E69u7eooxTjfjkIsTx92TqXnVsXPC6SlepfgnF_jjMsGuz2uePIioMjKW789R1qDtn_kP_lIxGgT_GEwtnnAJ7ZAxc_ELgfZTYiqj64L-3Ml-QbFaP6CzRgNyhcgWIk',
    rating: 4.8,
    category: 'Programming',
    progress: 65,
  },
  {
    id: 'cr2',
    title: 'Atomic Habits',
    author: 'James Clear',
    cover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDVJku5rabZRa7zLwtApR_MpJ7ma_ETaTXkAFIR5bfqtrdyn-Q6Rgh0tqo1gfvpfwZ-dGAPTLWGpuwv__VuwRZEuQKq4YvcOccHNe0kxsIqXK54d2if-s_wb-ZMAiTv-fDkQpyhsYp4GIj5Py9_yUH4u4dwQpifx6HGxnptcsdGvoqT6wBzIhTTw4M2X8d3DJPoETTlPVG1IwfkgG25kpX2fYYZhfKoW2YVhUAndLwrEJghLfWbRLU',
    rating: 4.7,
    category: 'Self Help',
    progress: 30,
  },
];
